[username]
format = " [â•­â”€$user]($style)@"
style_user = "#5e81ac"
style_root = "#5e81ac"
show_always = true

[hostname]
format = "[$hostname]($style) in "
style = "#8fbcbb"
trim_at = "-"
ssh_only = false
disabled = false

[directory]
style = "#5e81ac"
truncation_length = 0
truncate_to_repo = true
truncation_symbol = "repo: "

[git_status]
style = "white"
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
deleted = "x"

[cmd_duration]
disabled = true

[character]
success_symbol = " [â•°â”€>](#5e81ac)"
error_symbol = " [Ã—](#bf616a)"

[battery]
disabled = true

[aws]
symbol = "îŒ½ "
style = "#81a1c1"

[git_branch]
symbol = "ï˜ "
style = "#81a1c1"

[package]
symbol = "ğŸ“¦ "
style = "#81a1c1"

[php]
symbol = "î˜ˆ "
style = "#81a1c1"

[python]
symbol = "î˜† "
style = "#81a1c1"

[docker_context]
symbol = "ïŒˆ "
style = "#81a1c1"
